import './global.css';

export const metadata = {
  title: 'Flexible',
  description: 'Generated by FTOE',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
